// app/layout.tsx (বা layout.js)
import { Noto_Sans_Bengali } from 'next/font/google'; // ✅ এখানে import করতে হবে
import type { Metadata } from "next";
import "./globals.css";
import Header from '@/app/(pages)/Header/page.tsx';
import Footer from '@/app/(pages)/Footer/page.tsx';

// ফন্ট সেটআপ
const notoBengali = Noto_Sans_Bengali({ subsets: ['bengali'], weight: ['400','700'] });

export const metadata: Metadata = {
  title: "HANAFI MAZHAB",
  description: "Generated by create next app",
  icons: {
    icon: "/images/icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="bn" className={notoBengali.className}>  {/* className এখানে লাগবে */}
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
