// app/layout.tsx (বা layout.js)
import { Noto_Sans_Bengali } from 'next/font/google'; 
import type { Metadata } from "next";
import "./globals.css";
import Nav from './components/Navber/Nav';
import FooterPage from './components/Navber/FooterPage';


const notoBengali = Noto_Sans_Bengali({ subsets: ['bengali'], weight: ['400','700'] });

export const metadata: Metadata = {
  title: "HANAFI MAZHAB",
  description: "Generated by create next app",
  icons: {
    icon: "/images/icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="bn" className={notoBengali.className}>  
      <body>
        <Nav />
        {children}
        <FooterPage />
      </body>
    </html>
  );
}
